FROM python:3.6 AS base
WORKDIR /usr/src/app
RUN pip install --upgrade pip==9.0.*
RUN pip install --no-cache-dir \
    pytest \
    coverage
ARG cache=1
CMD ["pytest"]

ADD . .
RUN coverage run --source="curaPrintTimeEstimator" -m pytest
RUN coverage report --skip-covered --show-missing --fail-under=100
